In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns 
from collections import Counter

In [2]:
df = pd.read_csv("E:\Mini Project\AI-Expense-Tracker\ml_model\datasets/financial_transactions_train.csv")

In [3]:
df.head()

                              Transaction_Text       Label
0  Education loan EMI - INR 48395 - Ref 776405         EMI
1    NPS contribution - INR 24678 - Ref 554441  Investment
2   eBay online order - INR 21649 - Ref 863410    Shopping
3     Credit card EMI - INR 11866 - Ref 611973         EMI
4        Car loan EMI - INR 20537 - Ref 317418         EMI

In [5]:
import re 

def clean_transaction(text):

    text = str(text).lower()

    text = re.sub(r'inr\s*\d+', ' ', text)
    text = re.sub(r'ref\s*\d+', ' ', text)
    text = re.sub(r'\d+', ' ', text)
    text = re.sub(r'[^a-z\s]', ' ', text)
    text = re.sub(r'\s+', ' ', text)

    return text.strip()


df["clean_text"] = df["Transaction_Text"].apply(
    clean_transaction
)

In [6]:
df.head()

                              Transaction_Text       Label          clean_text
0  Education loan EMI - INR 48395 - Ref 776405         EMI  education loan emi
1    NPS contribution - INR 24678 - Ref 554441  Investment    nps contribution
2   eBay online order - INR 21649 - Ref 863410    Shopping   ebay online order
3     Credit card EMI - INR 11866 - Ref 611973         EMI     credit card emi
4        Car loan EMI - INR 20537 - Ref 317418         EMI        car loan emi

In [8]:
X = df["clean_text"]
y = df["Label"]

In [9]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("Training:", len(X_train))
print("Testing:", len(X_test))

Training: 4000
Testing: 1000

In [10]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(
    ngram_range=(1, 2),
    min_df=2,
    max_df=0.95,
    sublinear_tf=True
)

X_train_tfidf = tfidf.fit_transform(X_train)
X_test_tfidf = tfidf.transform(X_test)

In [11]:
from sklearn.linear_model import LogisticRegression

lr_model = LogisticRegression(
    max_iter=1000,
    random_state=42
)

lr_model.fit(
    X_train_tfidf,
    y_train
)

LogisticRegression(max_iter=1000, random_state=42)

In [12]:
y_pred = lr_model.predict(X_test_tfidf)

In [16]:
from sklearn.metrics import accuracy_score

lr_accuracy = accuracy_score(
    y_test,
    y_pred
)

print(f"Accuracy: {accuracy * 100:.2f}%")

Accuracy: 100.00%

In [17]:
from sklearn.metrics import classification_report

print(
    classification_report(
        y_test,
        y_pred,
        zero_division=0
    )
)

              precision    recall  f1-score   support

         EMI       1.00      1.00      1.00       200
        Food       1.00      1.00      1.00       194
  Investment       1.00      1.00      1.00       212
    Shopping       1.00      1.00      1.00       199
      Travel       1.00      1.00      1.00       195

    accuracy                           1.00      1000
   macro avg       1.00      1.00      1.00      1000
weighted avg       1.00      1.00      1.00      1000

In [33]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

lr_model = LogisticRegression(
    max_iter=1000,
    random_state=42
)

lr_model.fit(X_train_tfidf, y_train)

y_pred_lr = lr_model.predict(X_test_tfidf)

lr_accuracy = accuracy_score(y_test, y_pred_lr)
lr_precision = precision_score(
    y_test, y_pred_lr, average="weighted", zero_division=0
)
lr_recall = recall_score(
    y_test, y_pred_lr, average="weighted", zero_division=0
)
lr_f1 = f1_score(
    y_test, y_pred_lr, average="weighted", zero_division=0
)

print("Logistic Regression")
print("Accuracy :", lr_accuracy)
print("Precision:", lr_precision)
print("Recall   :", lr_recall)
print("F1 Score :", lr_f1)

Logistic Regression
Accuracy : 1.0
Precision: 1.0
Recall   : 1.0
F1 Score : 1.0

**Naive Bayes**

In [34]:
from sklearn.naive_bayes import MultinomialNB

nb_model = MultinomialNB()

nb_model.fit(
    X_train_tfidf,
    y_train
)

y_pred_nb = nb_model.predict(
    X_test_tfidf
)

In [35]:
nb_accuracy = accuracy_score(y_test, y_pred_nb)

nb_precision = precision_score(
    y_test,
    y_pred_nb,
    average="weighted",
    zero_division=0
)

nb_recall = recall_score(
    y_test,
    y_pred_nb,
    average="weighted",
    zero_division=0
)

nb_f1 = f1_score(
    y_test,
    y_pred_nb,
    average="weighted",
    zero_division=0
)

print("Naive Bayes")
print("Accuracy :", nb_accuracy)
print("Precision:", nb_precision)
print("Recall   :", nb_recall)
print("F1 Score :", nb_f1)

Naive Bayes
Accuracy : 1.0
Precision: 1.0
Recall   : 1.0
F1 Score : 1.0

**Linear SVM**

In [36]:
from sklearn.svm import LinearSVC

svm_model = LinearSVC(
    random_state=42
)

svm_model.fit(
    X_train_tfidf,
    y_train
)

y_pred_svm = svm_model.predict(
    X_test_tfidf
)

In [37]:
svm_accuracy = accuracy_score(
    y_test,
    y_pred_svm
)

svm_precision = precision_score(
    y_test,
    y_pred_svm,
    average="weighted",
    zero_division=0
)

svm_recall = recall_score(
    y_test,
    y_pred_svm,
    average="weighted",
    zero_division=0
)

svm_f1 = f1_score(
    y_test,
    y_pred_svm,
    average="weighted",
    zero_division=0
)

print("Linear SVM")
print("Accuracy :", svm_accuracy)
print("Precision:", svm_precision)
print("Recall   :", svm_recall)
print("F1 Score :", svm_f1)

Linear SVM
Accuracy : 1.0
Precision: 1.0
Recall   : 1.0
F1 Score : 1.0

**Random Forest**

In [38]:
from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier(
    n_estimators=200,
    random_state=42,
    n_jobs=-1
)

rf_model.fit(
    X_train_tfidf,
    y_train
)

RandomForestClassifier(n_estimators=200, n_jobs=-1, random_state=42)

In [39]:
y_pred_rf = rf_model.predict(
    X_test_tfidf
)

In [40]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score

rf_accuracy = accuracy_score(y_test, y_pred_rf)

rf_precision = precision_score(
    y_test,
    y_pred_rf,
    average="weighted",
    zero_division=0
)

rf_recall = recall_score(
    y_test,
    y_pred_rf,
    average="weighted",
    zero_division=0
)

rf_f1 = f1_score(
    y_test,
    y_pred_rf,
    average="weighted",
    zero_division=0
)

print("Random Forest")
print("Accuracy :", rf_accuracy)
print("Precision:", rf_precision)
print("Recall   :", rf_recall)
print("F1 Score :", rf_f1)

Random Forest
Accuracy : 1.0
Precision: 1.0
Recall   : 1.0
F1 Score : 1.0

**XG Boost**

In [41]:
import xgboost

print(xgboost.__version__)

3.2.0

In [47]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()

y_train_encoded = label_encoder.fit_transform(y_train)
y_test_encoded = label_encoder.transform(y_test)

print("Classes:", label_encoder.classes_)

Classes: ['EMI' 'Food' 'Investment' 'Shopping' 'Travel']

In [60]:
y_test_enc = label_encoder.transform(y_test)

xgb_accuracy = accuracy_score(y_test_enc, y_pred_xgb)
xgb_precision = precision_score(y_test_enc, y_pred_xgb, average="weighted", zero_division=0)
# ... etc

In [48]:
from xgboost import XGBClassifier

xgb_model = XGBClassifier(
    n_estimators=200,
    max_depth=6,
    learning_rate=0.1,
    random_state=42,
    eval_metric="mlogloss"
)

xgb_model.fit(
    X_train_tfidf,
    y_train_encoded
)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='mlogloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.1, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=6, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=200, n_jobs=None,
              num_parallel_tree=None, ...)

In [54]:
y_pred_xgb = xgb_model.predict(
    X_test_tfidf
)

In [55]:
y_pred_xgb = xgb_model.predict(
    X_test_tfidf
)

In [56]:
print(y_pred_xgb[:20])

[3 3 1 4 1 4 2 4 0 0 0 1 4 0 0 4 3 3 0 4]

In [61]:
xgb_accuracy = accuracy_score(
    y_test_enc,
    y_pred_xgb
)

xgb_precision = precision_score(
    y_test_enc,
    y_pred_xgb,
    average="weighted",
    zero_division=0
)

xgb_recall = recall_score(
    y_test_enc,
    y_pred_xgb,
    average="weighted",
    zero_division=0
)

xgb_f1 = f1_score(
    y_test_enc,
    y_pred_xgb,
    average="weighted",
    zero_division=0
)

print("XGBoost")
print("Accuracy :", xgb_accuracy)
print("Precision:", xgb_precision)
print("Recall   :", xgb_recall)
print("F1 Score :", xgb_f1)

XGBoost
Accuracy : 1.0
Precision: 1.0
Recall   : 1.0
F1 Score : 1.0

**KNN**

In [44]:
from sklearn.neighbors import KNeighborsClassifier

knn_model = KNeighborsClassifier(
    n_neighbors=5,
    metric="cosine",
    n_jobs=-1
)

knn_model.fit(
    X_train_tfidf,
    y_train
)

KNeighborsClassifier(metric='cosine', n_jobs=-1)

In [62]:
y_pred_knn = knn_model.predict(
    X_test_tfidf
)

In [46]:
knn_accuracy = accuracy_score(
    y_test,
    y_pred_knn
)

knn_precision = precision_score(
    y_test,
    y_pred_knn,
    average="weighted",
    zero_division=0
)

knn_recall = recall_score(
    y_test,
    y_pred_knn,
    average="weighted",
    zero_division=0
)

knn_f1 = f1_score(
    y_test,
    y_pred_knn,
    average="weighted",
    zero_division=0
)

print("KNN")
print("Accuracy :", knn_accuracy)
print("Precision:", knn_precision)
print("Recall   :", knn_recall)
print("F1 Score :", knn_f1)

KNN
Accuracy : 1.0
Precision: 1.0
Recall   : 1.0
F1 Score : 1.0

In [63]:
results = pd.DataFrame({
    "Model": [
        "Logistic Regression",
        "Naive Bayes",
        "Linear SVM",
        "Random Forest",
        "XGBoost",
        "KNN"
    ],
    "Accuracy": [
        lr_accuracy,
        nb_accuracy,
        svm_accuracy,
        rf_accuracy,
        xgb_accuracy,
        knn_accuracy
    ],
    "Precision": [
        lr_precision,
        nb_precision,
        svm_precision,
        rf_precision,
        xgb_precision,
        knn_precision
    ],
    "Recall": [
        lr_recall,
        nb_recall,
        svm_recall,
        rf_recall,
        xgb_recall,
        knn_recall
    ],
    "F1 Score": [
        lr_f1,
        nb_f1,
        svm_f1,
        rf_f1,
        xgb_f1,
        knn_f1
    ]
})

results = results.sort_values(
    by="F1 Score",
    ascending=False
).reset_index(drop=True)

results.round(4)

                 Model  Accuracy  Precision  Recall  F1 Score
0  Logistic Regression       1.0        1.0     1.0       1.0
1          Naive Bayes       1.0        1.0     1.0       1.0
2           Linear SVM       1.0        1.0     1.0       1.0
3        Random Forest       1.0        1.0     1.0       1.0
4              XGBoost       1.0        1.0     1.0       1.0
5                  KNN       1.0        1.0     1.0       1.0

In [64]:
test_df = pd.read_csv(
    "E:\Mini Project\AI-Expense-Tracker\ml_model\datasets/financial_transactions_test.csv"
)

print(test_df.shape)
print(test_df.head())

(1000, 2)
                              Transaction_Text       Label
0  Mobile EMI payment - INR 45866 - Ref 955127         EMI
1  Education loan EMI - INR 32772 - Ref 858630         EMI
2       Bike loan EMI - INR 12852 - Ref 259771         EMI
3    PPF contribution - INR 10392 - Ref 505075  Investment
4     NPS contribution - INR 3583 - Ref 580994  Investment

In [65]:
print(test_df.columns)

Index(['Transaction_Text', 'Label'], dtype='object')

In [66]:
test_df["clean_text"] = test_df["Transaction_Text"].apply(
    clean_transaction
)

In [67]:
X_external = tfidf.transform(
    test_df["clean_text"]
)

y_external = test_df["Label"]

In [68]:
pred_lr_external = lr_model.predict(
    X_external
)

In [69]:
pred_nb_external = nb_model.predict(
    X_external
)

In [70]:
pred_svm_external = svm_model.predict(
    X_external
)

In [71]:
pred_rf_external = rf_model.predict(
    X_external
)

In [72]:
pred_xgb_encoded = xgb_model.predict(
    X_external
)

pred_xgb_external = label_encoder.inverse_transform(
    pred_xgb_encoded.astype(int)
)

In [73]:
pred_knn_external = knn_model.predict(
    X_external
)

In [74]:
external_results = pd.DataFrame({
    "Model": [
        "Logistic Regression",
        "Naive Bayes",
        "Linear SVM",
        "Random Forest",
        "XGBoost",
        "KNN"
    ],
    "Accuracy": [
        accuracy_score(y_external, pred_lr_external),
        accuracy_score(y_external, pred_nb_external),
        accuracy_score(y_external, pred_svm_external),
        accuracy_score(y_external, pred_rf_external),
        accuracy_score(y_external, pred_xgb_external),
        accuracy_score(y_external, pred_knn_external)
    ]
})

external_results.sort_values(
    "Accuracy",
    ascending=False
).reset_index(drop=True)

                 Model  Accuracy
0  Logistic Regression       1.0
1          Naive Bayes       1.0
2           Linear SVM       1.0
3        Random Forest       1.0
4              XGBoost       1.0
5                  KNN       1.0

In [75]:
new_transactions = [
    "Had dinner at Domino's",
    "Paid Uber for office travel",
    "Bought clothes from Myntra",
    "Monthly Netflix subscription",
    "Paid electricity bill",
    "College semester fees",
    "Booked flight to Delhi",
    "Invested money in mutual fund",
    "Paid home loan EMI",
    "Bought medicines from pharmacy"
]

In [76]:
clean_new = [
    clean_transaction(text)
    for text in new_transactions
]

new_tfidf = tfidf.transform(clean_new)

In [77]:
pred_lr = lr_model.predict(new_tfidf)
pred_svm = svm_model.predict(new_tfidf)
pred_nb = nb_model.predict(new_tfidf)

for text, lr, svm, nb in zip(
    new_transactions,
    pred_lr,
    pred_svm,
    pred_nb
):
    print(f"{text}")
    print(f"  Logistic Regression: {lr}")
    print(f"  Linear SVM:          {svm}")
    print(f"  Naive Bayes:         {nb}")
    print()

Had dinner at Domino's
  Logistic Regression: Food
  Linear SVM:          Food
  Naive Bayes:         Food

Paid Uber for office travel
  Logistic Regression: Travel
  Linear SVM:          Travel
  Naive Bayes:         Travel

Bought clothes from Myntra
  Logistic Regression: Shopping
  Linear SVM:          Shopping
  Naive Bayes:         Shopping

Monthly Netflix subscription
  Logistic Regression: Investment
  Linear SVM:          Investment
  Naive Bayes:         Investment

Paid electricity bill
  Logistic Regression: Food
  Linear SVM:          Food
  Naive Bayes:         Food

College semester fees
  Logistic Regression: Investment
  Linear SVM:          Investment
  Naive Bayes:         Investment

Booked flight to Delhi
  Logistic Regression: Travel
  Linear SVM:          Travel
  Naive Bayes:         Travel

Invested money in mutual fund
  Logistic Regression: Investment
  Linear SVM:          Investment
  Naive Bayes:         Investment

Paid home loan EMI
  Logistic Regression: EMI
  Linear SVM:          EMI
  Naive Bayes:         EMI

Bought medicines from pharmacy
  Logistic Regression: Investment
  Linear SVM:          Investment
  Naive Bayes:         Investment

In [78]:
print(df["Label"].value_counts())

Label
Investment    1058
EMI            999
Shopping       997
Travel         975
Food           971
Name: count, dtype: int64

In [79]:
print(df["Label"].unique())

['EMI' 'Investment' 'Shopping' 'Travel' 'Food']

In [80]:
for category in df["Label"].unique():
    print("\n==============================")
    print("CATEGORY:", category)
    print("==============================")
    
    print(
        df[df["Label"] == category]["Transaction_Text"]
        .head(15)
        .to_string(index=False)
    )

==============================
CATEGORY: EMI
==============================
 Education loan EMI - INR 48395 - Ref 776405
    Credit card EMI - INR 11866 - Ref 611973
       Car loan EMI - INR 20537 - Ref 317418
    Credit card EMI - INR 17358 - Ref 776864
      Bike loan EMI - INR 43378 - Ref 474875
        Car loan EMI - INR 2924 - Ref 360073
 Education loan EMI - INR 22576 - Ref 633337
    Credit card EMI - INR 17886 - Ref 328648
 Mobile EMI payment - INR 31480 - Ref 429340
        Car loan EMI - INR 8843 - Ref 989212
Consumer durable EMI - INR 4552 - Ref 830073
  Personal loan EMI - INR 25938 - Ref 822729
 Laptop EMI payment - INR 19410 - Ref 248151
       Appliance EMI - INR 2296 - Ref 141407
       Home loan EMI - INR 5365 - Ref 370001

==============================
CATEGORY: Investment
==============================
        NPS contribution - INR 24678 - Ref 554441
  Stock market investment - INR 3515 - Ref 966760
Fixed deposit investment - INR 15964 - Ref 968375
        PPF contribution - INR 25330 - Ref 784494
          PPF contribution - INR 875 - Ref 642625
 Stock market investment - INR 37521 - Ref 810126
  Demat account transfer - INR 33298 - Ref 275461
        PPF contribution - INR 12209 - Ref 487335
     Share trading debit - INR 23155 - Ref 156695
Fixed deposit investment - INR 20884 - Ref 445733
  Demat account transfer - INR 26265 - Ref 921268
         Mutual fund SIP - INR 48751 - Ref 951124
            ETF purchase - INR 40271 - Ref 354712
         PPF contribution - INR 1232 - Ref 910459
             ETF purchase - INR 4220 - Ref 748914

==============================
CATEGORY: Shopping
==============================
       eBay online order - INR 21649 - Ref 863410
    Electronics purchase - INR 20742 - Ref 689191
  Amazon online shopping - INR 22559 - Ref 120999
    Electronics purchase - INR 39269 - Ref 989426
Lifestyle store purchase - INR 26094 - Ref 220872
    Electronics purchase - INR 47790 - Ref 959509
       Flipkart purchase - INR 37268 - Ref 578791
  Ajio clothing purchase - INR 10303 - Ref 182936
   Mall shopping payment - INR 21336 - Ref 773116
Lifestyle store purchase - INR 47417 - Ref 997648
Lifestyle store purchase - INR 41191 - Ref 678897
    Retail store shopping - INR 6913 - Ref 455102
    Mall shopping payment - INR 6823 - Ref 550381
    Electronics purchase - INR 37557 - Ref 202203
       Flipkart purchase - INR 25592 - Ref 926764

==============================
CATEGORY: Travel
==============================
      Metro card recharge - INR 31664 - Ref 344965
      Bus ticket purchase - INR 46011 - Ref 472828
         Uber ride payment - INR 8021 - Ref 122858
       Hotel stay booking - INR 24826 - Ref 796007
      Metro card recharge - INR 10686 - Ref 376985
      Metro card recharge - INR 27136 - Ref 481669
          Ola cab booking - INR 15316 - Ref 395391
         Uber ride payment - INR 4081 - Ref 691869
MakeMyTrip travel booking - INR 45956 - Ref 123819
        Airport taxi fare - INR 19111 - Ref 524939
         Rapido bike ride - INR 46983 - Ref 819378
          Ola cab booking - INR 10081 - Ref 505637
         Hotel stay booking - INR 907 - Ref 383013
MakeMyTrip travel booking - INR 30436 - Ref 279105
         Rapido bike ride - INR 14231 - Ref 483802

==============================
CATEGORY: Food
==============================
     Grocery food items - INR 24352 - Ref 450218
     Grocery food items - INR 15852 - Ref 169806
    Cafe coffee purchase - INR 3139 - Ref 599962
Restaurant dine-in bill - INR 19055 - Ref 558430
     Grocery food items - INR 24040 - Ref 271096
       KFC online order - INR 31494 - Ref 579992
    Dominos pizza order - INR 15575 - Ref 251220
    Dominos pizza order - INR 16805 - Ref 141133
   Cafe coffee purchase - INR 35729 - Ref 588406
       KFC online order - INR 22651 - Ref 892243
   Cafe coffee purchase - INR 15609 - Ref 618466
   Cafe coffee purchase - INR 22681 - Ref 981647
     Grocery food items - INR 40505 - Ref 250520
   Swiggy order payment - INR 42451 - Ref 439001
        Bakery purchase - INR 49152 - Ref 227939

In [81]:
print(test_df["Label"].value_counts())

Label
Food          217
EMI           204
Shopping      204
Investment    189
Travel        186
Name: count, dtype: int64